package common

const (
	REQUEST_ID       = "REQUEST-ID"
	REQUEST_USER     = "REQUEST-USER"
	REQUEST_URI      = "REQUEST-URI"
	REQUEST_METHOD   = "REQUEST-METHOD"
	REQUEST_TIMEZONE = "REQUEST-TZ"
	RESOURCE_IP      = "RESOURCE-IP"
)
